version: '3.1'

volumes:
  data: {}
  cache:
    driver: local

services:
  db-mongo:
    image: mongo
    restart: always
    container_name: database-brrs-${NODE_ENV}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME_MONGO}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD_MONGO}
      MONGO_INITDB_DATABASE: ${DATABASE_INITDB_DATABASE}
    ports:
      - ${DATABASE_PORT_MONGO}:27017
    volumes:
      - data:/var/lib/mongodb/data
